### PR TITLE
Change to test env instead of prod

### PR DESCRIPTION
**Pull request by atodd-noms**
Changes NODE_ENV from production to test, because we need to have some test-only util stuff

### CODE REVIEW

**Comment by glenjamin** [comment]
The `production` setting also changes a bunch of defaults in express and other apps to be more production-like.

You might be better off having a `ENABLE_TEST_STUFF` flag which is independent

**Comment by atodd-noms** [comment]
Changed it to use an explicit env var as suggested

**Comment by glenjamin** [comment]
So I went to apply this, and hit a type error because terraform casts all template parameters into strings.

I decided this was a decent enough push to make me refactor the definitions to use the newly supported native resources for app services - which will make app config much easier to manage.

After doing this to the mock env, it highlighted a difference from code to reality:

```
  ~ azurerm_app_service.ui
      app_settings.%:                       "11" => "12"
      app_settings.ENABLE_TEST_UTILS:       "" => "1"
      app_settings.NODE_ENV:                "test" => "production"
      app_settings.NOMIS_API_URL:           "https://licences-nomis-mocks.herokuapp.com/elite2api" => "https://licences-nomis-mocks.herokuapp.com/"
```

Is this safe to apply or do I need to update the code more?

**Comment by atodd-noms** [comment]
The one ending with /elite2api is the correct one so I've pushed a change to fix that.
The rest looks right.

**Pull request merged**
